-- Pharmacy Inventory Management System - database schema
-- Exactly the six tables defined in the project specification.

CREATE DATABASE IF NOT EXISTS pharmacy_ims
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE pharmacy_ims;

-- Staff and patient accounts. Passwords are stored only as bcrypt hashes.
CREATE TABLE IF NOT EXISTS users (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name          VARCHAR(100) NOT NULL,
  email         VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role          ENUM('staff', 'patient') NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB;

-- Medication catalog / inventory.
CREATE TABLE IF NOT EXISTS medications (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name          VARCHAR(150) NOT NULL,
  category      VARCHAR(100) NOT NULL,
  quantity      INT NOT NULL,
  unit_price    DECIMAL(10, 2) NOT NULL,
  expiry_date   DATE NOT NULL,
  supplier_info VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT chk_medications_quantity CHECK (quantity >= 0),
  CONSTRAINT chk_medications_price CHECK (unit_price >= 0)
) ENGINE=InnoDB;

-- One chat session per patient; staff_id is set when a staff member replies.
CREATE TABLE IF NOT EXISTS chat_sessions (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  patient_id INT UNSIGNED NOT NULL,
  staff_id   INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_sessions_patient (patient_id),
  CONSTRAINT fk_chat_sessions_patient FOREIGN KEY (patient_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_sessions_staff   FOREIGN KEY (staff_id)   REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Persisted chat log (FR 5.1).
CREATE TABLE IF NOT EXISTS chat_messages (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  chat_session_id INT UNSIGNED NOT NULL,
  sender_id       INT UNSIGNED NOT NULL,
  content         TEXT NOT NULL,
  timestamp       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_chat_messages_session (chat_session_id, timestamp),
  CONSTRAINT fk_chat_messages_session FOREIGN KEY (chat_session_id) REFERENCES chat_sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_messages_sender  FOREIGN KEY (sender_id)       REFERENCES users (id)         ON DELETE CASCADE
) ENGINE=InnoDB;

-- Historical sales used to train the forecasting model (FR 6.1).
CREATE TABLE IF NOT EXISTS sales_history (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  medication_id INT UNSIGNED NOT NULL,
  quantity_sold INT NOT NULL,
  date          DATE NOT NULL,
  PRIMARY KEY (id),
  KEY idx_sales_history_medication_date (medication_id, date),
  CONSTRAINT fk_sales_history_medication FOREIGN KEY (medication_id) REFERENCES medications (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Alerts generated by the forecasting job (FR 6.2).
CREATE TABLE IF NOT EXISTS reorder_alerts (
  id                   INT UNSIGNED NOT NULL AUTO_INCREMENT,
  medication_id        INT UNSIGNED NOT NULL,
  predicted_date       DATE NOT NULL,
  days_until_threshold INT NOT NULL,
  status               ENUM('active', 'dismissed') NOT NULL DEFAULT 'active',
  PRIMARY KEY (id),
  KEY idx_reorder_alerts_medication_status (medication_id, status),
  CONSTRAINT fk_reorder_alerts_medication FOREIGN KEY (medication_id) REFERENCES medications (id) ON DELETE CASCADE
) ENGINE=InnoDB;
