/**
 * /api/alerts - staff-only reorder alerts generated by the forecast job (FR 6.2).
 */
const { Router } = require('express');
const alertController = require('../controllers/alertController');
const authenticate = require('../middleware/authenticate');
const requireRole = require('../middleware/requireRole');
const { ROLES } = require('../../../shared/constants.json');

const router = Router();

router.use(authenticate, requireRole(ROLES.STAFF));

router.get('/', alertController.list);
router.patch('/:id/dismiss', alertController.dismiss);

module.exports = router;
